default_platform(:android)

platform :android do

    desc "Lane for distributing app using Firebase App Distributions"
    lane :firebase_distribution do
        gradle(task: "clean assembleRelease")
        firebase_app_distribution(
          app: ENV["FIREBASE_APP_ID"],
          firebase_cli_token: ENV["FIREBASE_TOKEN"],
          groups: "",
          release_notes: "Git commit: #{last_git_commit[:abbreviated_commit_hash]}",
        )
    end
  
end