name: Publish Android to Firebase App Distribution
on:
  push:
    branches:
      - main
jobs:
  release-android:
    name: Build and release Android app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.x"
      - name: Install firebase CLI
        run: npm install -g firebase-tools
      - name: Install Fastlane
        run: cd android && gem uninstall fastlane --all --executables && gem install fastlane --version 2.160 --user-install && gem uninstall fastlane-plugin-firebase_app_distribution && gem install fastlane-plugin-firebase_app_distribution --user-install && fastlane add_plugin firebase_app_distribution &&  bundle install && cd ..
      - name: Decode google-services.json
        env:
          FIREBASE_SECRET: ${{ secrets.FIREBASE_SECRET }}
        run: ls -la && echo $FIREBASE_SECRET > android/app/google-services.json
      - name: Install packages
        run: yarn install
      - name: build release
        run: cd android && ./gradlew assembleRelease
      - name: Upload artifact to Firebase App Distribution
        env:
          API_KEY: ${{ secrets.API_KEY }},
          AUTH_DOMAIN: ${{ secrets.AUTH_DOMAIN }},
          DATABASE_URL: ${{ secrets.DATABASE_URL }},
          PROJECT_ID: ${{ secrets.PROJECT_ID }},
          STORAGE_BUCKET: ${{ secrets.STORAGE_BUCKET }},
          MESSAGING_SENDER_ID: ${{ secrets.MESSAGING_SENDER_ID }},
          APP_ID: ${{ secrets.APP_ID }},
          MEASUREMENT_ID: ${{ secrets.MEASUREMENT_ID }},
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID}},
          FIREBASE_GROUPS: ${{ secrets.FIREBASE_GROUPS}},
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN}},
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: local
          file: app/build/outputs/apk/release/app-release.apk
