name: Publish Android to Firebase App Distribution
on:
  push:
    branches:
      - main
jobs:
  release-android:
    name: Build and release Android app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.x"
      - name: Install Fastlane
        run: cd android && bundle install && cd ..
      - name: Decode google-services.json
        env:
          FIREBASE_SECRET: ${{ secrets.FIREBASE_SECRET }}
        run: ls -la && echo $FIREBASE_SECRET > android/app/google-services.json
      - name: Install packages
        run: yarn install
      - name: Execute Fastlane command
        env:
          API_KEY: ${{ secrets.API_KEY }},
          AUTH_DOMAIN: ${{ secrets.AUTH_DOMAIN }},
          DATABASE_URL: ${{ secrets.DATABASE_URL }},
          PROJECT_ID: ${{ secrets.PROJECT_ID }},
          STORAGE_BUCKET: ${{ secrets.STORAGE_BUCKET }},
          MESSAGING_SENDER_ID: ${{ secrets.MESSAGING_SENDER_ID }},
          APP_ID: ${{ secrets.APP_ID }},
          MEASUREMENT_ID: ${{ secrets.MEASUREMENT_ID }},
        run: cd android && bundle exec fastlane beta
