name: Publish Android to Firebase App Distribution
on:
  push:
    branches:
      - main
jobs:
  distribute:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.7"
      - name: install firebase tool
        run: |
          yarn global add firebase-tools
      - name: setup fastlane
        run: cd android && bundle install && cd ..
      - name: Decode google-services.json
        env:
          FIREBASE_SECRET: ${{ secrets.FIREBASE_SECRET }}
        run: echo $FIREBASE_SECRET > android/app/google-services.json
      - name: Install packages
        run: yarn install
      - name: Upload artifact to Firebase App Distribution
        env:
          API_KEY: ${{ secrets.API_KEY }},
          AUTH_DOMAIN: ${{ secrets.AUTH_DOMAIN }},
          DATABASE_URL: ${{ secrets.DATABASE_URL }},
          PROJECT_ID: ${{ secrets.PROJECT_ID }},
          STORAGE_BUCKET: ${{ secrets.STORAGE_BUCKET }},
          MESSAGING_SENDER_ID: ${{ secrets.MESSAGING_SENDER_ID }},
          APP_ID: ${{ secrets.APP_ID }},
          MEASUREMENT_ID: ${{ secrets.MEASUREMENT_ID }},
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID}},
          FIREBASE_GROUPS: ${{ secrets.FIREBASE_GROUPS}},
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN}},
        run: cd android && bundle exec fastlane android firebase_distribution
